### ISSUE TITLE
Embedded Timestamps

### ISSUE THREAD

**Issue by chris-asdf** [woheller69/TimeLapseCamera#17] opened 2023-05-18 08:39 UTC
Hi,

thanks for creating this app!
Would it be possible to add a optional feature to embed timestamps in on of the corners of the recorded pictures/videos? Or did I miss that option...

All the best
Chris

**Comment by woheller69** [comment] 2023-05-18 08:50
Duplicate of #15

**Closed by woheller69** 2023-05-18 08:50 UTC
